const router = require('express').Router();
const crypto = require('crypto');
const Razorpay = require('razorpay');
const Fee = require('../models/Fee');
const Student = require('../models/Student');
const { auth } = require('../middleware/auth');

// Lazily initialise the Razorpay instance so the app can start even if the
// env vars are not yet configured.
let razorpayInstance = null;
function getRazorpay() {
  if (!razorpayInstance) {
    if (!process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET) {
      throw new Error('Razorpay keys not configured. Add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET to your .env file.');
    }
    razorpayInstance = new Razorpay({
      key_id: process.env.RAZORPAY_KEY_ID,
      key_secret: process.env.RAZORPAY_KEY_SECRET,
    });
  }
  return razorpayInstance;
}

// ── POST /api/payment/create-order ───────────────────────────────────────────
// Creates a Razorpay order for the student's total pending fees.
router.post('/create-order', auth, async (req, res) => {
  try {
    const { amount } = req.body;
    if (!amount || isNaN(amount) || Number(amount) <= 0) {
      return res.status(400).json({ message: 'Invalid amount' });
    }

    const rzp = getRazorpay();
    // Razorpay receipt must be <= 40 chars; keep it compact and unique.
    const userTail = String(req.user._id || '').slice(-8);
    const receipt = `rcpt_${userTail}_${Date.now().toString(36)}`;

    const order = await rzp.orders.create({
      amount: Math.round(Number(amount) * 100), // Razorpay expects paise (1 INR = 100 paise)
      currency: 'INR',
      receipt,
      notes: {
        studentId: req.user._id.toString(),
        email: req.user.email || '',
      },
    });

    res.json({
      orderId: order.id,
      amount: order.amount,
      currency: order.currency,
      keyId: process.env.RAZORPAY_KEY_ID,
    });
  } catch (error) {
    const msg = error?.error?.description || error?.message || 'Could not create Razorpay order';
    console.error('Razorpay create-order error:', msg);
    res.status(500).json({ message: msg });
  }
});

// ── POST /api/payment/verify ──────────────────────────────────────────────────
// Verifies the Razorpay payment signature using HMAC-SHA256 and marks all
// pending fees for the student as paid.
router.post('/verify', auth, async (req, res) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return res.status(400).json({ message: 'Missing payment verification details' });
    }

    // Verify the HMAC-SHA256 signature generated by Razorpay
    const body = razorpay_order_id + '|' + razorpay_payment_id;
    const expectedSignature = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(body)
      .digest('hex');

    if (expectedSignature !== razorpay_signature) {
      return res.status(400).json({ message: 'Payment verification failed: invalid signature' });
    }

    // Get all pending / overdue fees for this student
    const fees = await Fee.find({
      studentId: req.user._id,
      status: { $in: ['pending', 'overdue'] },
    }).sort({ dueDate: 1 });

    if (fees.length === 0) {
      return res.json({ message: 'No pending fees to update', updated: 0, paymentId: razorpay_payment_id });
    }

    // Mark ALL pending/overdue fees as paid for this payment
    const paidDate = new Date().toISOString().split('T')[0];
    for (let i = 0; i < fees.length; i++) {
      const fee = fees[i];
      fee.status = 'paid';
      fee.paidDate = paidDate;
      fee.method = 'Razorpay';
      fee.transactionId = fees.length > 1
        ? `${razorpay_payment_id}_${i + 1}`
        : razorpay_payment_id;
      await fee.save();
    }

    // Keep Student.feesPaid in sync
    const allPaidFees = await Fee.find({ studentId: req.user._id, status: 'paid' });
    const totalPaidAmount = allPaidFees.reduce((sum, f) => sum + (f.amount || 0), 0);
    await Student.findByIdAndUpdate(req.user._id, { feesPaid: totalPaidAmount });

    res.json({
      message: `Payment verified. All ${fees.length} fee(s) marked as paid.`,
      updated: fees.length,
      paymentId: razorpay_payment_id,
      orderId: razorpay_order_id,
    });
  } catch (error) {
    console.error('Razorpay verify error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// ── GET /api/payment/key ──────────────────────────────────────────────────────
// Exposes only the public key ID to the frontend (never the secret).
router.get('/key', auth, (req, res) => {
  const keyId = process.env.RAZORPAY_KEY_ID;
  if (!keyId || keyId.includes('YOUR_KEY')) {
    return res.status(503).json({ message: 'Razorpay not configured on this server' });
  }
  res.json({ keyId });
});

module.exports = router;
